name: Nuclei - DAST Scan

on:
  push: 
    branches: [ main ]

jobs:
  nuclei-scan: 
    name: "Scan live web app for security flaws"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
    
      - name: "Start containers"
        run: docker-compose -f "docker-compose.yml" up -d --build
    
      - name: "Dynamic Security Testing"
        uses: jeprimustikaa/nuclei-action@main
        with: 
          target: "http://localhost:8080"
      
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: nuclei.sarif
